### ISSUE TITLE
[BUG] Unable to import ConnectedUIRouter 

### ISSUE THREAD

**Issue by IdeaHunter** [ui-router/redux#1]
`@uirouter/redux` version: **0.1.0**
The following code from homepage isn't working
```es6
import { ConnectedUIRouter } from '@uirouter/redux/lib/react';
```
I was only able to find ConnectUIRouter under `_bundles` folder, but not under `lib`:
![image](https://user-images.githubusercontent.com/10799080/32390194-85c1bfde-c0de-11e7-9730-f199db5bff5d.png)

**Comment by elboman** [comment]
Hi, thanks for reporting the bug. I must have made some error when publishing on `npm` 😅 

I'll ping you once fixed!

**Comment by elboman** [comment]
I've just publish `0.1.1` with all the missing files. Thanks again for the report!

Let me know if you find any other issue or if you see any way we can improve the lib.

**Comment by IdeaHunter** [comment]
Thank you for the fix! Just tested and found it working 👍
