### ISSUE TITLE
Parameter example?

### ISSUE THREAD

**Issue by trevor-ryan-burkholder** [ui-router/redux#2]
Can we get an example of how to use a route parameter to filter props in a component? e.g. filter todos by whether they're completed or not?

Or would the ui-router/react examples suffice for this?

**Comment by elboman** [comment]
You don't need to use `ui-router/redux` to achieve this, unless I'm missing something.

You can read the params via the `transition` prop that is injected in the routed component like this:
```jsx
render () {
	const params = this.props.transition.params();
	return (
    	<div>
        	{todos.filter(todo => todo.status === params.status).map(todo => (
				<Todo data={todo} key={todo.id} />
			))}
        </div>
    );
}
```

**Comment by trevor-ryan-burkholder** [comment]
Thanks! I'll give this a try. I wasn't sure if the transition prop was only necessary if you were doing animations.

**Comment by elboman** [comment]
Yeah, the `transition` prop refers to the router transition and not animations of any kind
